import 'dart:ui' as ui;

import 'package:flutter/services.dart' show rootBundle;
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import '../../models/member.dart';
import '../locale/locale_service.dart';

/// Builds a shareable PDF of the member roster (name, school, designation,
/// phone) — the same idea as [FinancePdfService] but for the member list
/// rather than payments. Kept as its own small service rather than folded
/// into FinancePdfService since this isn't a financial document.
///
/// Bengali handling matches FinancePdfService: the `pdf` package can't shape
/// Bengali conjuncts, so any Bengali cell is rendered through Flutter's own
/// text engine into an image and embedded; pure-Latin cells stay real text.
class MemberPdfService {
  MemberPdfService._();

  static const _assocName =
      'Bangladesh Teachers Association, Baniyachong Branch, Habiganj';

  static const double _imgScale = 3.0;

  static final RegExp _bengali = RegExp(r'[ঀ-৿]');
  static bool _hasBengali(String s) => _bengali.hasMatch(s);

  static pw.Font? _font;

  static Future<pw.Font> _loadFont() async {
    _font ??= pw.Font.ttf(await rootBundle.load('assets/fonts/Kalpurush.ttf'));
    return _font!;
  }

  static Future<pw.Widget> _line(
    String text, {
    double fontSize = 9,
    PdfColor color = PdfColors.black,
    bool bold = false,
    double maxWidth = 240,
  }) async {
    final shown = text.isEmpty ? '-' : text;
    if (!_hasBengali(shown)) {
      return pw.Text(
        shown,
        style: pw.TextStyle(
          fontSize: fontSize,
          color: color,
          fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal,
        ),
      );
    }

    final uiColor = ui.Color.fromARGB(
      255,
      (color.red * 255).round(),
      (color.green * 255).round(),
      (color.blue * 255).round(),
    );
    final builder = ui.ParagraphBuilder(ui.ParagraphStyle(
      textAlign: ui.TextAlign.left,
      fontSize: fontSize * _imgScale,
      fontFamily: 'Kalpurush',
      fontWeight: bold ? ui.FontWeight.bold : ui.FontWeight.normal,
    ))
      ..pushStyle(ui.TextStyle(
        color: uiColor,
        fontFamily: 'Kalpurush',
        fontSize: fontSize * _imgScale,
      ))
      ..addText(shown);
    final paragraph = builder.build()
      ..layout(ui.ParagraphConstraints(width: maxWidth * _imgScale));

    final w = paragraph.longestLine.ceil().clamp(1, 100000);
    final h = paragraph.height.ceil().clamp(1, 100000);

    final recorder = ui.PictureRecorder();
    ui.Canvas(recorder).drawParagraph(paragraph, ui.Offset.zero);
    final image = await recorder.endRecording().toImage(w, h);
    final bytes = await image.toByteData(format: ui.ImageByteFormat.png);

    return pw.Image(
      pw.MemoryImage(bytes!.buffer.asUint8List()),
      width: w / _imgScale,
      height: h / _imgScale,
      dpi: 72 * _imgScale,
    );
  }

  /// Shares a PDF listing [members]: name, school, designation, phone.
  static Future<void> shareMemberList(List<Member> members) async {
    final font = await _loadFont();

    final nameCells = <pw.Widget>[for (final m in members) await _line(m.name, bold: true)];
    final schoolCells = <pw.Widget>[for (final m in members) await _line(m.schoolName)];
    final designationCells = <pw.Widget>[for (final m in members) await _line(m.designation)];
    final footer = await _line(
      LocaleService.isEnglish ? 'Generated by the Oikko app.' : 'Oikko অ্যাপ থেকে তৈরি।',
      fontSize: 9,
      color: PdfColors.grey600,
      maxWidth: 400,
    );

    final doc = pw.Document();
    doc.addPage(
      pw.MultiPage(
        theme: pw.ThemeData.withFont(base: font, bold: font),
        pageFormat: PdfPageFormat.a4,
        build: (context) => [
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(_assocName,
                  style: pw.TextStyle(fontSize: 13, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 2),
              pw.Text('Member List', style: const pw.TextStyle(fontSize: 11, color: PdfColors.blue800)),
              pw.SizedBox(height: 6),
              pw.Text(
                'Generated: ${DateFormat('dd MMM yyyy, hh:mm a').format(DateTime.now())}',
                style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
              ),
              pw.Divider(color: PdfColors.grey400),
            ],
          ),
          pw.SizedBox(height: 8),
          pw.Text('${members.length} members',
              style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600)),
          pw.SizedBox(height: 14),
          pw.Table(
            border: pw.TableBorder.all(color: PdfColors.grey300, width: 0.5),
            columnWidths: const {
              0: pw.FlexColumnWidth(2.6),
              1: pw.FlexColumnWidth(3),
              2: pw.FlexColumnWidth(2),
              3: pw.FlexColumnWidth(2),
            },
            children: [
              pw.TableRow(
                decoration: const pw.BoxDecoration(color: PdfColors.blue800),
                children: [
                  for (final h in ['Name', 'School', 'Designation', 'Phone'])
                    pw.Padding(
                      padding: const pw.EdgeInsets.symmetric(horizontal: 6, vertical: 5),
                      child: pw.Text(h,
                          style: pw.TextStyle(
                              fontSize: 10, fontWeight: pw.FontWeight.bold, color: PdfColors.white)),
                    ),
                ],
              ),
              for (var i = 0; i < members.length; i++)
                pw.TableRow(
                  children: [
                    pw.Padding(
                      padding: const pw.EdgeInsets.symmetric(horizontal: 6, vertical: 5),
                      child: nameCells[i],
                    ),
                    pw.Padding(
                      padding: const pw.EdgeInsets.symmetric(horizontal: 6, vertical: 5),
                      child: schoolCells[i],
                    ),
                    pw.Padding(
                      padding: const pw.EdgeInsets.symmetric(horizontal: 6, vertical: 5),
                      child: designationCells[i],
                    ),
                    pw.Padding(
                      padding: const pw.EdgeInsets.symmetric(horizontal: 6, vertical: 5),
                      child: pw.Text(members[i].phone.isEmpty ? '-' : members[i].phone,
                          style: const pw.TextStyle(fontSize: 9)),
                    ),
                  ],
                ),
            ],
          ),
          pw.SizedBox(height: 20),
          pw.Divider(color: PdfColors.grey400),
          footer,
        ],
      ),
    );

    await Printing.sharePdf(bytes: await doc.save(), filename: 'oikko-member-list.pdf');
  }
}
